[package]
name = "switchhosts-rs"
version = "0.1.0"
authors = ["z-nieyuyao"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
tui-textarea = "0.7.0"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
